<?php 
    $h1 = 'Koncept umetnika';
    $audio = 'Zvuk pluća puštan na izložbi u Šok galeriji';
    $concept1 = '<h2>ORGANIZAM #1 Proces: Bol pluća</h2>
    <p>Crteži ORGANIZAM #1 se zasnivaju na introspektivnoj naraciji i intimnoj vizuelizaciji bola. Osnovno polazište je ličan doživljaj bliže prošlosti u toku prehlade, odnosno gripa, kroz prisećanje i rekonstrukciju doživljenog bola. Klasična prehlada sa kašljem mišljena kroz crtež dobija svoj vizuelni oblik kao imaginarni ili pseudo medicinski izveštaj.  Bol je predstavljen kroz sedam crteža – sedam dana bolesti, oblikovanih kao medicinski atlas. </p>
    <p>U toku prehlade vodila sam kratki dnevnik gde sam svakodnevno beležila kako se osećam i opisivala fiziološko stanje organizma. Zahvaljujući tim beleškama nastaju crteži i tekst koji ih prati.</p>
    <p>Crteži predstavljaju sećanje na bol, likovnu varijaciju trenutka, medicinsku vizuelizaciju i oblik bolesti koji pripadaju imaginaciji iako se oslanjaju na stvarno stanje. Crteži nisu nastali kao ilustracija naučnog rada stoga anatomski prikaz tela i bolesti kao i tekst koji ih prati ne moraju biti tačni.</p>
    <p>Medicinski elementi koje sam koristila i razvijala u svom radu prikazuju ličnu percepciju humane fiziologije. Pored bola, rad se bavi i stanjem izolacije ili samoizolacije koja je čest pratilac bolesti. Ovde se ne misli samo na gest zahtevan kao deo procesa lečenja već i kao mentalno stanje obolelog, teskoba koju oboleli može da oseća i kao posledica suočavanja sa procesima degradacije tela.</p>
    <p>Zvuk šuma pluća kao pratilac crteža, upotpunjuje osećaj teskobe. Cilj je da teskoba postane pored unutrašnje i spoljašnja. Spoljašna teskoba kod posmatrača izazvana ulaskom u organizam. </p>
    <p>Crteži i zvuk disanja prikazuju zavirivanje u organizam, ulazak u telo, pri čemu je mali galerijski prostor od izuzetnog značaja. Stišnjenost prostora, zvuk i vizuelni sadržaj kod posmatrača mogu da izazovu  efekat psihosomatske reakcije: promenu srčanog rada, destabilizaciju krvnog pritiska, promene u disanju koje bi pratile zvuk disanja koji se čuje u prostoru. Idealne uslove za uspešnu instalaciju izložbe i stvaranje ovog efekta do sada sam imala jedino u Šok galeriji Art klinike u Novom Sadu. </p>';
    $concept2 = '<h2>OLTAR ZA DERMATITIS -Slike o ožiljcima s ožiljcima-</h2>
    <p>
        Slike ili preciznije crteži na platnu „Oltar za dermatitis“ deo su triptiha  i zasnivaja se na ličnom doživljaju bola. Bol je strahota svake individue i civilizacije, a ujedno i njihov roditelj. Arhetip bola se uvek iznova pojavljuje u umetnosti, rešenja u likovnom stvaralaštvu su različita, ali suština bola je uvek ista. Želela sam da svoju čestu ispiracuju doživljaja bola prikažem kroz medicinski crtež ispirisan osmanskom medicinskom ilustracijom i estetikom dalekog istoka. Crtež „Oltar za dermatitis“ predstavlja sećanje na bol koje je kao takvo prirodno iskrivljeno i nerealno.
    </p>
    <p>
        Dokumentujući zdravstveno stanje i situacije u kojima sam se nalazila pravim crtež na platnu čija je likovna poetika bliska osmanskim iluminiranim rukopisima za medicinske knjige Şerafeddin Sabuncuoğlua i japanskim estampama. Didaktična odlika koja postoji na osmanskim medicinskim crtežima u vidu podučavanja lekara o ponašanju prema pacijentu, o fizičkom položaju lekara u odnosu na pacijenta tokom neke medicinske intervencije prisutna je i na mojim crtežima. Ovde se ne radi o anatomskom prikazu tela niti vizuelizaviji kožnog obolenja već o odnosu pacijenta i bolesti, samoizolaciji i potrazi za izlečenjem, o susretu lekara i pacijenta, o prihvatanju bolesti. Analiza bolesti kroz tri etape, gde je treća gotovo inicijacijska, ponovno rađanje kroz prihvatanje. Beli čisti hrt koji liže ruku je biblijska scena o leproznima. Ali za razliku od psa koji prilazi leproznom, prihvata ga i leči, ili su zajedno odbačeni od drštva ja psu dajem ulogu farmakologije odnosno dermatologije koja nema rešenje za neka oboljenja samo mnogo medicinskih preparata. Crtež prikazuje trenutak spoznaje da lek za dermatitis ne postoji i da je ironično, jedino izlečenje prihvatanje hroničnog stanja. Stavljanje maske koju oboleli dobija od svog lekara samo je jedan gest koji simbolizje čitav niz mera koje su neophodne da bi se bolest samo prikrila, ne zaista izlečila. 
    </p>
    <p>
        Pećina zbog svoje tajnovitosti, nedostupnosti i mraka simbolizije utočište za obolelog, gde se sklanja od očiju javnosti. Takođe, ona je materica iz koje će se oboleli ponovo roditi sa maskom na licu, odnosno postaće prihvatljiv drugima i sebi, bez straha da će biti izopšten. Duga, kao simobol nadanja i svetla ukazuje na optimizam obolelog, odnosno na prihvatanje. Beli čisti hrt simbolizuje farmaceutsku industriju, bojažljivo se prikrada, liže ruku dok je ne odgrize.
    </p>
    <p>
        Triptih „Oltar za dermatitis“ je spretom nesretnih okolnosti oštećen. Sve tri slike u donjem uglu imaju oštećenja ili kako ih nazivam ožiljke.
    </p>';
    $concept3 = '<h2>„COLORFUL BOOKS“ -Likovni dnevnici-</h2>
    <p>
        „COLORFUL BOOKS“ je skup vizuelnih dnevnika objedinjenih pod jednim imenom, nastalih u periodu od 2010. do 2019. Ono što je specifično za njih jeste da su nastali u različitim gradovima: Novom Sadu, Smederevu, Istanbulu i Beogradu, a oni su svojim geografskim i kulturološkim razlikama uticali na vizuelni jezik i simboliku. Svaka lokacija predstavlja životni trenutak, odluke i interesovanja koje su od lične važnosti. Crteži se zasnivaju na introspektivnoj naraciji i intimnoj vizuelizaciji tela i duha.
    </p>
    <p>
        Vremenski prelaz od prvog do poslednjeg dnevnika prikazuje postepeni razvoj i promene u likovnom izrazu. Smenjuju se različiti uticaji i interesovanja. Stečena znanja na polju istorije umetnosti posebno islamske minijature za medicinske knjige koje su me zainteresovale nakon nastanka mojih prvih „medicinskih“ crteža imala su najveci uticaj na moj rad. Taj uticaj se dalje razvijao pa se potraga proširila na daleki istok, a sa dalekog istoka sa savremene atlase humane fiziologije.
    </p>
    <p>
        Naracija izgrađena oko istorije i kulture Istanbula, posebno minijatura, stvorila je dinamičan kolorit i simboliku koja naginje ka mitološkim scenama. Te mitološke scene su zapravo stvarni događaji kojima sam prisustvovala a o kojima je razmišljano kroz perspektivu minijatura. Dnevnici iz Smedereva su neka vrsta sabiranja ličnih želja i težnji, snovi u groznici. Dnevnik iz Beograda je angažovanog tipa, gde kroz crtež i tekst u obliku parole pripoveda o događajima koji su se zbili u toku zime i proleća 2018-19.
    </p>
    <p>
        Na stranicama knjige Astečka astrologija crtačkom intervencijom nastaju promene u vizuelnoj i tekstualnoj formi. Knjiga menja svoj oblik i značenje te tako postaje Crni Pas. U pitanju je igra rečima i slikama unutar knjige koja se crtačkom inetvencijom transformiše, i jedan banalan tekst pretvaraju u nadrealnu naraciju. Ovakav crtački pristup ima potencijala za dalje razvijanje i izbor knjige kao materijala je od presudnog značaja jer je tekst taj koji vodi trasformaciju. Prepuštanje tekstu i crtežima koje sam zatekla u knjizi Astečka astrologija odveli su me do Crnog Psa. Moja intervencija i manipulacija tekstom dozvoljena je u meri u kojoj to originalni tekst daje. Pokušaj da sa drugom knjigom iz iste edicije uradim potpuno drugačiji projekat za mene je bilo gotovo nemoguće. Vremenski razmak u nastanku druge knjige nije bio od pomoći, loš tekst, nemaštovit i gotovo identičan u obema knjigama davao je mahom iste rezultate, pa su na neki nacin Crni Pas i Cvet svojevrsni likovni blizanci.
    </p>';
?>